version: '2'

services:
 web:
      build: ./code
      user: root
      command: bash -c "./proxy" 
      volumes:
        - ./code:/code
        - ./logs:/var/log/erss
      ports:
        - "12345:12345"
        